name: .NET Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: #comando que permite a execução manual do pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOTNET_VERSION: '8.0.x'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      # reusable workflow
      uses: maalcantara/reusable_workflows/.github/workflows/setup-dotnet-sdk.yml@main
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dotnet-format
      run: dotnet tool install --global dotnet-format

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Publish the project
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-app
        path: ./publish
