name: .NET Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Permite execução manual do pipeline

jobs:
  setup-dotnet-sdk:
    uses: maalcantara/reusable_workflow/.github/workflows/setup-dotnet-sdk.yml@main
    with:
      dotnet_version: '8.0.x'

  build:
    runs-on: ubuntu-latest
    needs: setup-dotnet-sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dotnet-format
        run: dotnet tool install --global dotnet-format

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Publish the project
        run: dotnet publish --configuration Release --output ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-app
          path: ./publish
